version: '3'
services:
  app:
    build: .
    tty: true
    privileged: true
    # environment:
    #   - DISPLAY=${DISPLAY}
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ./build:/build
    working_dir: /build
